---
- name: Deploy to production
  hosts: prod
  become: true
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
  tasks:
    - name: Log in to Docker registry
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull the Docker image from Docker Hub
      docker_image:
        name: harshadeelu/edureka-cicd:latest
        source: pull

    - name: Run the Docker container in detached mode
      docker_container:
        name: website
        image: harshadeelu/edureka-cicd:latest
        state: started
        detach: yes
